module;

#include <disconf.hpp>

#include <unordered_map>
#include <system_error>
#include <functional>
#include <filesystem>
#include <exception>
#include <charconv>
#include <fstream>
#include <memory>
#include <ranges>
#include <limits>
#include <format>
#include <vector>
#include <regex>
#include <tuple>
#include <array>

#define MKHEX(x) (std::format("{:#x}", (x)))

module Application;

import disxx.utility.ini.Parser;

import disxx.utility.error.NullPointerError;
import disxx.loader.executable.ExecutableFile;
import disxx.loader.macho.Loader;
import disxx.disasm.Disassembler;
import disxx.ui.backend.GLUTContext;
import disxx.ui.SourceEditor;
import disxx.ui.TabbedPane;
import disxx.ui.MainWindow;
import disxx.ui.TextInput;
import disxx.ui.Button;
import disxx.ui.Label;
import disxx.ui.Frame;
import disxx.ui.Menu;
import disxx.ui.Widget;
import ScriptEngine;
import FileInput;
import DisLog;

// Miscellaneous function(s)
namespace
{
	inline std::tuple<std::string, std::string, std::string> splitver(const std::string &version) noexcept
	{
		std::smatch groups{};
		std::regex_match(version, groups, std::regex{R"(^(\d+)\.(\d+)\.(\d+)$)"});
		// Return major minor and patchlevel strings
		return std::make_tuple(groups[1], groups[2], groups[3]);
	}
}

// The only one instance
Application *Application::s_pInstance{nullptr};

Application::Application(void) noexcept(false)
	: m_Window{disxx::ui::utility::Vec2<int>{800, 600}, "dis++ v" __DISXX_VERSION__}
	, m_Logger{}
	, m_pInput{std::make_unique<FileInput>()}
{ this->m_pInput->SetCallback([] -> void { Application::Init(); }); }

void Application::Disassemble(const std::filesystem::path &path) noexcept(false)
{
	// Check if path exists
	if (std::error_code errc{}; !std::filesystem::exists(path, errc)) [[unlikely]]
		throw std::filesystem::filesystem_error{"FileNotFoundError", errc};

	// Just take the ptr, so I shouldn't cast it every time
	auto *pLabels{static_cast<disxx::ui::SourceEditor *>(s_pInstance->m_Window.GetWidgets().at(1).get())};
	pLabels->ClearText();

	disxx::ui::SourceEditor editor{};
	editor.SetColor(0.2f, 0.2f, 0.2f);
	editor.AddLine(";{:*<64}", "");
   	editor.AddLine(";  This file was generated by the dis++ disassembler");
   	editor.AddLine(";\tCopyright (C) ultimatum");
   	editor.AddLine(";  Dis++ version: " __DISXX_VERSION__ " - {}", path.string());
   	editor.AddLine(";{:*<64}", "");
   	editor.AddLine("");
   	editor.AddLine(";{:=<63};", "");
	editor.AddLine("");

	// Load the executable
    disxx::loader::macho::Loader ldr;
	ldr.LoadFile(path);
	
	// Load metadata of the executable
	auto info{ldr.LoadMetadata()};
	editor.AddLine(";{:*<28}METADATA{:*<28}", "", "");
	editor.AddLine(";  File path: {}", path.string());
	editor.AddLine(";  File type: Mach-O {}", ldr.GetFileType());	
	editor.AddLine(";  Target OS: {}, v{}", info.GetPlatformName(), info.GetPlatformMinVersion());
	ldr
		.LoadImageBase()
		.and_then
		(
			[&editor](const auto &addr) -> std::optional<long long int>
			{ 
				editor.AddLine(";\tImage base: {}", MKHEX(addr));
				return addr;
			}
		).or_else
		(
			[&editor](void) -> std::optional<long long int>
			{
				editor.AddLine("\tImage base: unknown");
				return std::nullopt; 
			}
		);
	for (const auto &[name, version] : info.GetBuildTools())
		editor.AddLine(";  Build tool: {}, v{}", name, version);
	editor.AddLine(";{:*<64}", "");
	editor.AddLine("");

	const auto &[platformMajor, platformMinor, _]{::splitver(info.GetPlatformMinVersion())};
	const auto &[sdkMajor, sdkMinor, _]{::splitver(info.GetSDKVersion())};
	editor.AddLine
	(
		"<color value=\"0.6 0.6 0.2 1.0\">.build_version</color>"
		" {}, <color value=\"0.7 0.2 0.1 1.0\">{}</color>,"
		" <color value=\"0.7 0.2 0.1 1.0\">{}</color>"
		" sdk_version <color value=\"0.7 0.2 0.1 1.0\">{}</color>,"
		" <color value=\"0.7 0.2 0.1 1.0\">{}</color>",
		info.GetPlatformName()
			| std::views::all
			| std::views::transform(::tolower)
			| std::ranges::to<std::string>(),
		platformMajor,
		platformMinor,
		sdkMajor,
		sdkMinor
	);

	for (auto &section : ldr.LoadData().GetSections())
	{
		const auto name{section.GetName()};
		editor.AddLine("");
		editor.AddLine("<color value=\"0.6 0.6 0.2 1.0\">.section</color> {}", name);
		editor.AddLine("");

		// these sections are considered as executable
		if (name == "__TEXT,__text" || name == "__TEXT,__stubs")
		{
    		std::unordered_map<std::uint64_t, std::string> names;
    		for (const auto &label : section.GetLabels())
    		    names[label.GetAddress()] = label.GetName();
		
			for (const auto &label : section.GetLabels())
		    {
		        pLabels->AddLine
				(
					"<color value=\"0.7 0.6 0.2 1.0\">{}</color>:"
					"<color value=\"0.8 0.6 0.2 1.0\">{:#016}</color>:"
					"<color value=\"0.6 0.6 0.2 1.0\">{}</color>",
					section.GetName(),
					label.GetAddress(),
					label.GetName()
				);

		        editor.AddLine("<color value=\"0.6 0.6 0.2 1.0\">{}</color>:", label.GetName());

				disxx::disasm::Disassembler disasm{};
				const auto &vec
				{
					label.GetData<std::uint32_t>()
						| std::views::all
						| std::views::transform([](const auto &bytes) -> auto { return disxx::disasm::Bytes{bytes}; })
						| std::ranges::to<std::vector<disxx::disasm::Bytes>>()
				};
	   		    for (disxx::disasm::Address addr{label.GetAddress()}; const auto &bytes : vec)
    		    {
					if (const auto &insn{disasm.Disassemble(bytes, addr++)}) [[likely]]
					{
						auto mnemonic
						{
							[&insn](void) -> std::string
							{
								auto str{std::format("{}", *insn)};
								
								static const std::regex regs{R"(((b|h|s|d|q|v|w|x)\d{1,2})|(sp)|((w|x)zr))"};
								for (std::sregex_iterator it{str.begin(), str.end(), regs}, end{}; it != end; ++it)
								{
									// Check if it was accidentally confused with immediate operand
									if (const auto &prev{str.at(it->position() - 1uz)}; prev == 'x' || std::isdigit(prev) || (prev >= 97 && prev <= 102)) [[unlikely]]
										continue;
									// Check if a number of the register is valid
									else if (auto n{0ull}; std::from_chars(it->str().data() + 1, it->str().data() + it->str().size() - 1, n)) [[likely]]
										if (n > 31) [[unlikely]]
											continue;

									str = std::regex_replace
									(
										str,
										std::regex{it->str()},
										std::format("<color value=\"0.3 0.7 0.7 1.0\">{}</color>", it->str())
									);
								}

								static const std::regex imms{R"(#-?((0x[a-f0-9]+)|(\d+\.\d+)))"};
								for (std::sregex_iterator it{str.begin(), str.end(), imms}, end{}; it != end; ++it)
								{
									// Check if it's a pc-relevant address (using .value_or(0) instead of .value() method)
									if (const auto insnAddr{insn->GetProgramCounterRelevantAddress()}; insnAddr && std::string{"#"} + MKHEX(insnAddr.value_or(0)) == it->str())
									{
										str = std::regex_replace
										(
											str,
											std::regex{it->str()},
											std::format("<color value=\"0.6 0.6 0.2 1.0\">{}</color>", it->str())
										);
									}
									else
									{
										str = std::regex_replace
										(
											str,
											std::regex{it->str()},
											std::format("<color value=\"0.7 0.2 0.1 1.0\">{}</color>", it->str())
										);
									}
								}

								return str;
							}()
						};
						
						if (auto insnAddr{insn->GetProgramCounterRelevantAddress()})
    		        	{
    		            	if (auto it{names.find(*insnAddr)}; it != names.end())
    		            	{
    		            	    editor.AddLine
    		            	    (
									"<color value=\"0.7 0.7 0.7 1.0\">|</color>\t{}\t\t"
									"<color value=\"0.7 0.7 0.7 1.0\">; {:#x}</color>",
    		            	        std::regex_replace
									(
										mnemonic,
										std::regex
										{
											std::string{"#"}
												+ MKHEX(*insnAddr)
										},
										it->second
									),
									label.GetAddress()
								);
	   		            	    
								continue;
	   		            	}
	   		        	}

						editor.AddLine("<color value=\"0.7 0.7 0.7 1.0\">|</color>\t{}", mnemonic);
					}
					else	
						editor.AddLine("<color value=\"0.7 0.7 0.7 1.0\">|</color>\t{}", insn.error().what());
				}
    		}
		}
		else
		{
			for (const auto &label : section.GetLabels())
			{
				pLabels->AddLine
				(
					"<color value=\"0.7 0.6 0.2 1.0\">{}</color>:"
					"<color value=\"0.8 0.6 0.2 1.0\">{:#016}</color>:"
					"<color value=\"0.6 0.6 0.2 1.0\">{}</color>",
					name,
					label.GetAddress(),
					label.GetName()
				);
				editor.AddLine("<color value=\"0.6 0.6 0.2 1.0\">{}</color>:", label.GetName());

				for (const auto &byte : label.GetData<std::uint8_t>())
				{
					editor.AddLine
					(
						"<color value=\"0.7 0.7 0.7 1.0\">|</color>"
						"\t<color value=\"0.6 0.6 0.2 1.0\">.byte </color>"
						"<color value=\"0.7 0.2 0.1 1.0\">{:#02x}</color>{}",
						byte,
						std::isprint(byte) && !std::isspace(byte)
							? std::format("\t<color value=\"0.7 0.7 0.7 1.0\">; \'{:c}\'</color>", byte)
							: std::string{}
					);
				}
			}
		}
	}

	const auto [width, height]{s_pInstance->m_Window.GetSize()};
	pLabels->Resize(disxx::ui::utility::Vec2<float>{width * 1.f, height * 0.2f});

	disxx::ui::Tab tab{};
	tab.SetColor(0.2f, 0.2f, 0.2f);
	tab.SetText(path.string());
	tab.SetTextArea(std::move(editor));

	static_cast<disxx::ui::TabbedPane *>
	(
		s_pInstance
			->m_Window
			.GetWidgets()
			.begin()
			->get()
	)->Push(std::move(tab));
}

void Application::Init(void) noexcept(false)
{
	// Destroy the previous window
    std::filesystem::path path{};
	if (s_pInstance->m_pInput) [[likely]]
	{
		path = s_pInstance->m_pInput->GetPath();
		s_pInstance->m_pInput.reset();
	}

	s_pInstance->m_Window.SetVisible(true);
	const auto [width, height]{s_pInstance->m_Window.GetSize()};
	
	{
		disxx::ui::TabbedPane pane
		{
			0.f,
			0.f,
			width * 1.f,
			height * 0.7f
		};
		pane.SetColor(0.2f, 0.2f, 0.2f);

		s_pInstance->m_Window.AddWidget(std::make_unique<disxx::ui::TabbedPane>(pane));
	}

	{
		disxx::ui::SourceEditor labels
		{
			0.f,
			height * 0.75f,
			width * 1.f,
			height * 0.2f
		};
		labels.SetColor(0.2f, 0.2f, 0.2f);
		
		s_pInstance->m_Window.AddWidget(std::make_unique<disxx::ui::SourceEditor>(labels));
	}

	{
		disxx::ui::Menu menu
		{
			0.f,
			height * 0.97f,
			width * 0.05f,
			height * 0.03f
		};
		menu.SetColor(0.2f, 0.2f, 0.2f);
		menu.SetText("File");

		disxx::ui::MenuEntry open
		{
			"Open...",
			[] -> void
			{
				// Do nothing if the entry has been activated
				static bool openActive{false};
				if (openActive) [[unlikely]]
					return;

				#ifdef BACKEND_CTX_GLUT
					const auto [w, h]{disxx::ui::backend::GLUTContext::GetWindowSize()};
				#endif

				disxx::ui::Frame frame
				{
					w / 4,
					h / 4,
					w / 2,
					h / 2
				};
				frame.SetColor(0.2f, 0.2f, 0.2f);
				s_pInstance->m_Window.AddWidget(std::make_unique<disxx::ui::Frame>(frame));

				disxx::ui::Label upper
				{
					w / 2.f,
					h / 2.f + 100.f,
					0.f,
					0.f
				};
				upper.SetColor(1.f, 1.f, 1.f);
				upper.SetText("Select an executable to disassemble");
				s_pInstance->m_Window.AddWidget(std::make_unique<disxx::ui::Label>(upper));
				
				disxx::ui::Label label
				{
					w / 4.f + 70.f,
					h / 2.f + 45.f,
					0.f,
					0.f
				};
				label.SetColor(0.3f, 0.3f, 0.3f);
				label.SetText("Executable:");
				s_pInstance->m_Window.AddWidget(std::make_unique<disxx::ui::Label>(label));

				disxx::ui::Button ok
				{
					w / 2.f + w / 5.f - 100.f,
					h / 2.f - h / 5.f,
					100.f,
					40.f
				};
				ok.SetColor(0.3f, 0.3f, 0.3f);
				ok.SetText("OK");
				ok.SetCallback
				(
					disxx::ui::Button::Trigger::BTN_CLICKED,
					[](const disxx::ui::Widget *const) -> void
					{
						if (s_pInstance->m_Window.GetWidgets().size() < 5) [[unlikely]]
							return;

						const auto p
						{
							static_cast<disxx::ui::TextInput *>
							(
								(
									s_pInstance
										->m_Window
										.GetWidgets()
										.rbegin()
								)->get()
							)->GetText()

						};

						for (const auto _ : std::views::iota(0, 5))
							s_pInstance->m_Window.GetWidgets().pop_back();
						
						s_pInstance->Disassemble(std::filesystem::path{p});
					
						openActive = false;
					}
				);
				s_pInstance->m_Window.AddWidget(std::make_unique<disxx::ui::Button>(ok));

				disxx::ui::Button cancel
				{
					w / 2 - w / 5.f,
					h / 2 - h / 5.f,
					100.f,
					40.f
				};
				cancel.SetColor(0.3f, 0.3f, 0.3f);
				cancel.SetText("Cancel");
				cancel.SetCallback
				(
					disxx::ui::Button::Trigger::BTN_CLICKED,
					[](const disxx::ui::Widget *const) -> void
					{
						if (s_pInstance->m_Window.GetWidgets().size() < 5) [[unlikely]]
							return;

						for (const auto _ : std::views::iota(0, 5))
							s_pInstance->m_Window.GetWidgets().pop_back();

						openActive = false;
					}
				);
				s_pInstance->m_Window.AddWidget(std::make_unique<disxx::ui::Button>(cancel));

				disxx::ui::TextInput input
				{
					w / 3.f + 50.f,
					h / 2.f + 25.f,
					250.f,
					40.f
				};
				input.SetColor(0.3f, 0.3f, 0.3f);
				s_pInstance->m_Window.AddWidget(std::make_unique<disxx::ui::TextInput>(input));

				openActive = true;
			}
		};
		open.SetColor(0.2f, 0.2f, 0.2f);
		menu.PushEntry(std::move(open));

		disxx::ui::MenuEntry save
		{
			"Save source",
			[] -> void
			{
				// Do nothing if the entry has been activated
				static bool saveActive{false};
				if (saveActive) [[unlikely]]
					return;

				#ifdef BACKEND_CTX_GLUT
					const auto [w, h]{disxx::ui::backend::GLUTContext::GetWindowSize()};
				#endif

				disxx::ui::Frame frame
				{
					w / 4,
					h / 4,
					w / 2,
					h / 2
				};
				frame.SetColor(0.2f, 0.2f, 0.2f);
				s_pInstance->m_Window.AddWidget(std::make_unique<disxx::ui::Frame>(frame));

				disxx::ui::Label upper
				{
					w / 2.f,
					h / 2.f + 100.f,
					0.f,
					0.f
				};
				upper.SetColor(1.f, 1.f, 1.f);
				upper.SetText("Save source");
				s_pInstance->m_Window.AddWidget(std::make_unique<disxx::ui::Label>(upper));
				
				disxx::ui::Label label
				{
					w / 4.f + 70.f,
					h / 2.f + 45.f,
					0.f,
					0.f
				};
				label.SetColor(0.3f, 0.3f, 0.3f);
				label.SetText("Save as:");
				s_pInstance->m_Window.AddWidget(std::make_unique<disxx::ui::Label>(label));

				disxx::ui::Button ok
				{
					w / 2.f + w / 5.f - 100.f,
					h / 2.f - h / 5.f,
					100.f,
					40.f
				};
				ok.SetColor(0.3f, 0.3f, 0.3f);
				ok.SetText("OK");
				ok.SetCallback
				(
					disxx::ui::Button::Trigger::BTN_CLICKED,
					[](const disxx::ui::Widget *const) -> void
					{
						if (s_pInstance->m_Window.GetWidgets().size() < 5) [[unlikely]]
							return;

						const auto p
						{
							static_cast<disxx::ui::TextInput *>
							(
								(
									s_pInstance
										->m_Window
										.GetWidgets()
										.rbegin()
								)->get()
							)->GetText()

						};

						for (const auto _ : std::views::iota(0, 5))
							s_pInstance->m_Window.GetWidgets().pop_back();
					
						if (const auto tab{static_cast<disxx::ui::TabbedPane *>(s_pInstance->m_Window.GetWidgets().begin()->get())->GetActiveTab()}) [[likely]]
						{
							std::fstream file{std::string{p}, std::fstream::out | std::fstream::binary | std::fstream::trunc};
							if (const std::error_code errc{}; !file.is_open()) [[unlikely]]
								throw std::filesystem::filesystem_error{"FileError", errc};

							const auto area{tab->get().GetTextArea()};
							for (const auto &line : area.GetLines())
								for (const auto &ch : std::regex_replace(line, std::regex{R"(\|)"}, "") + "\n")
									file.write(&ch, sizeof(char));
						}
	
						saveActive = false;
					}
				);
				s_pInstance->m_Window.AddWidget(std::make_unique<disxx::ui::Button>(ok));

				disxx::ui::Button cancel
				{
					w / 2 - w / 5.f,
					h / 2 - h / 5.f,
					100.f,
					40.f
				};
				cancel.SetColor(0.3f, 0.3f, 0.3f);
				cancel.SetText("Cancel");
				cancel.SetCallback
				(
					disxx::ui::Button::Trigger::BTN_CLICKED,
					[](const disxx::ui::Widget *const) -> void
					{
						if (s_pInstance->m_Window.GetWidgets().size() < 5) [[unlikely]]
							return;

						for (const auto _ : std::views::iota(0, 5))
							s_pInstance->m_Window.GetWidgets().pop_back();

						saveActive = false;
					}
				);
				s_pInstance->m_Window.AddWidget(std::make_unique<disxx::ui::Button>(cancel));

				disxx::ui::TextInput input
				{
					w / 3.f + 50.f,
					h / 2.f + 25.f,
					250.f,
					40.f
				};
				input.SetColor(0.3f, 0.3f, 0.3f);
				s_pInstance->m_Window.AddWidget(std::make_unique<disxx::ui::TextInput>(input));

				saveActive = true;
			}
		};
		save.SetColor(0.2f, 0.2f, 0.2f);
		menu.PushEntry(std::move(save));

		disxx::ui::MenuEntry script
		{
			"Script",
			[] -> void
			{
				// Do nothing if the entry has been activated
				static bool scriptActive{false};
				if (scriptActive) [[unlikely]]
					return;

				#ifdef BACKEND_CTX_GLUT
					const auto [w, h]{disxx::ui::backend::GLUTContext::GetWindowSize()};
				#endif

				disxx::ui::Frame frame
				{
					w / 4,
					h / 4,
					w / 2,
					h / 2
				};
				frame.SetColor(0.2f, 0.2f, 0.2f);
				s_pInstance->m_Window.AddWidget(std::make_unique<disxx::ui::Frame>(frame));

				disxx::ui::Label upper
				{
					w / 2.f,
					h / 2.f + 100.f,
					0.f,
					0.f
				};
				upper.SetColor(1.f, 1.f, 1.f);
				upper.SetText("Load script file");
				s_pInstance->m_Window.AddWidget(std::make_unique<disxx::ui::Label>(upper));
				
				disxx::ui::Label label
				{
					w / 4.f + 70.f,
					h / 2.f + 45.f,
					0.f,
					0.f
				};
				label.SetColor(0.3f, 0.3f, 0.3f);
				label.SetText("Path:");
				s_pInstance->m_Window.AddWidget(std::make_unique<disxx::ui::Label>(label));

				disxx::ui::Button ok
				{
					w / 2.f + w / 5.f - 100.f,
					h / 2.f - h / 5.f,
					100.f,
					40.f
				};
				ok.SetColor(0.3f, 0.3f, 0.3f);
				ok.SetText("Load");
				ok.SetCallback
				(
					disxx::ui::Button::Trigger::BTN_CLICKED,
					[](const disxx::ui::Widget *const) -> void
					{
						if (s_pInstance->m_Window.GetWidgets().size() < 5) [[unlikely]]
							return;

						const auto p
						{
							static_cast<disxx::ui::TextInput *>
							(
								(
									s_pInstance
										->m_Window
										.GetWidgets()
										.rbegin()
								)->get()
							)->GetText()

						};

						for (const auto _ : std::views::iota(0, 5))
							s_pInstance->m_Window.GetWidgets().pop_back();

						static ScriptEngine engine{};
						engine.ExecFile(p);
	
						scriptActive = false;
					}
				);
				s_pInstance->m_Window.AddWidget(std::make_unique<disxx::ui::Button>(ok));

				disxx::ui::Button cancel
				{
					w / 2 - w / 5.f,
					h / 2 - h / 5.f,
					100.f,
					40.f
				};
				cancel.SetColor(0.3f, 0.3f, 0.3f);
				cancel.SetText("Cancel");
				cancel.SetCallback
				(
					disxx::ui::Button::Trigger::BTN_CLICKED,
					[](const disxx::ui::Widget *const) -> void
					{
						if (s_pInstance->m_Window.GetWidgets().size() < 5) [[unlikely]]
							return;

						for (const auto _ : std::views::iota(0, 5))
							s_pInstance->m_Window.GetWidgets().pop_back();

						scriptActive = false;
					}
				);
				s_pInstance->m_Window.AddWidget(std::make_unique<disxx::ui::Button>(cancel));

				disxx::ui::TextInput input
				{
					w / 3.f + 50.f,
					h / 2.f + 25.f,
					250.f,
					40.f
				};
				input.SetColor(0.3f, 0.3f, 0.3f);
				s_pInstance->m_Window.AddWidget(std::make_unique<disxx::ui::TextInput>(input));

				scriptActive = true;
			}
		};
		script.SetColor(0.2f, 0.2f, 0.2f);
		menu.PushEntry(std::move(script));

		disxx::ui::MenuEntry exit
		{
			"Exit",
			[] -> void { std::exit(0); }
		};
		exit.SetColor(0.2f, 0.2f, 0.2f);
		menu.PushEntry(std::move(exit));

		s_pInstance->m_Window.AddWidget(std::make_unique<disxx::ui::Menu>(menu));
	}

	{
		disxx::ui::Menu menu
		{
			width * 0.05f,
			height * 0.97f,
			width * 0.05f,
			height * 0.03f
		};
		menu.SetColor(0.2f, 0.2f, 0.2f);
        menu.SetText("View");

		s_pInstance->m_Window.AddWidget(std::make_unique<disxx::ui::Menu>(menu));
	}

	if (!path.empty())	
		s_pInstance->Disassemble(path);

    s_pInstance
		->m_Window
		.Redisplay();
}

int Application::Exec(void) const noexcept(false)
{
	this->m_Window.Exec();
	return EXIT_SUCCESS;
}
