module;

#include <disconf.hpp>

#include <unordered_map>
#include <system_error>
#include <functional>
#include <filesystem>
#include <exception>
#include <charconv>
#include <memory>
#include <ranges>
#include <limits>
#include <format>
#include <vector>
#include <regex>
#include <tuple>
#include <array>

#include <print>

#define MKHEX(x) (std::format("{:#x}", (x)))

module Application;

import disxx.utility.ini.Parser;

import disxx.utility.error.NullPointerError;
import disxx.loader.executable.ExecutableFile;
import disxx.loader.macho.Loader;
import disxx.disasm.Disassembler;
import disxx.ui.backend.GLUTContext;
import disxx.ui.SourceEditor;
import disxx.ui.MainWindow;
import disxx.ui.TextInput;
import disxx.ui.Button;
import disxx.ui.Menu;
import disxx.ui.Widget;
import FileInput;
import DisLog;

// Miscellaneous function(s)
namespace
{
	static constexpr std::unique_ptr<disxx::ui::MainWindow> pNull{nullptr};

	inline std::tuple<std::string, std::string, std::string> splitver(const std::string &version) noexcept
	{
		std::smatch groups;
		std::regex_match(version, groups, std::regex{R"(^(\d+)\.(\d+)\.(\d+)$)"});
		// Return major minor and patchlevel strings
		return std::make_tuple(groups[1], groups[2], groups[3]);
	}
}

// The only one instance
Application *Application::s_pInstance{nullptr};

Application::Application(void) noexcept(false)
	: m_pWindow{std::ref(const_cast<std::unique_ptr<disxx::ui::MainWindow> &>(pNull))}
	, m_Logger{}
	, m_pInput{nullptr}
{
	// Init file input window
    this->m_pInput = FileInput::Init();
    this->m_pInput->SetCallback([] -> void { Application::Init(); });
}

Application::~Application(void) noexcept
{
	if (this->m_pInput) [[likely]]
		delete this->m_pInput;
	this->m_pInput = nullptr;
}

void Application::Disassemble(const std::filesystem::path &path) noexcept(false)
{
	// Check if path exists
	if (std::error_code errc{}; !std::filesystem::exists(path, errc)) [[unlikely]]
		throw std::filesystem::filesystem_error{"FileNotFoundError", errc};

	// Just take the ptrs, so I shouldn't cast it every time
	auto *pLabels{static_cast<disxx::ui::SourceEditor *>(s_pInstance->m_pWindow.get()->GetWidgets().begin()->get())};
	auto *pEditor{static_cast<disxx::ui::SourceEditor *>(s_pInstance->m_pWindow.get()->GetWidgets().rbegin()->get())};

	pLabels->ClearText();
	pEditor->ClearText();

	pEditor->SetColor(0.2f, 0.2f, 0.2f);
	pEditor->AddLine(";{:*<64}", "");
   	pEditor->AddLine(";  This file was generated by the dis++ disassembler");
   	pEditor->AddLine(";\tCopyright (C) ultimatum");
   	pEditor->AddLine(";  Dis++ version: " __DISXX_VERSION__);
   	pEditor->AddLine(";{:*<64}", "");
   	pEditor->AddLine("");
   	pEditor->AddLine(";{:=<63};", "");
	pEditor->AddLine("");

	// Load the executable
    disxx::loader::macho::Loader ldr;
	ldr.LoadFile(path);
	
	// Load metadata of the executable
	auto info{ldr.LoadMetadata()};
	pEditor->AddLine(";{:*<28}METADATA{:*<28}", "", "");
	pEditor->AddLine(";  File path: {}", path.string());
	pEditor->AddLine(";  File type: Mach-O {}", ldr.GetFileType());	
	pEditor->AddLine(";  Target OS: {}, v{}", info.GetPlatformName(), info.GetPlatformMinVersion());
	ldr
		.LoadImageBase()
		.and_then
		(
			[pEditor](const auto &addr) -> std::optional<long long int>
			{ 
				pEditor->AddLine(";\tImage base: {}", MKHEX(addr));
				return addr;
			}
		).or_else
		(
			[pEditor](void) -> std::optional<long long int>
			{
				pEditor->AddLine("\tImage base: unknown");
				return std::nullopt; 
			}
		);
	for (const auto &[name, version] : info.GetBuildTools())
		pEditor->AddLine(";  Build tool: {}, v{}", name, version);
	pEditor->AddLine(";{:*<64}", "");
	pEditor->AddLine("");

	const auto &[platformMajor, platformMinor, _]{::splitver(info.GetPlatformMinVersion())};
	const auto &[sdkMajor, sdkMinor, _]{::splitver(info.GetSDKVersion())};
	pEditor->AddLine
	(
		"<color value=\"0.6 0.6 0.2 1.0\">.build_version</color>"
		" {}, <color value=\"0.7 0.2 0.1 1.0\">{}</color>,"
		" <color value=\"0.7 0.2 0.1 1.0\">{}</color>"
		" sdk_version <color value=\"0.7 0.2 0.1 1.0\">{}</color>,"
		" <color value=\"0.7 0.2 0.1 1.0\">{}</color>",
		info.GetPlatformName()
			| std::views::all
			| std::views::transform(::tolower)
			| std::ranges::to<std::string>(),
		platformMajor,
		platformMinor,
		sdkMajor,
		sdkMinor
	);

	for (auto &section : ldr.LoadData().GetSections())
	{
		const auto name{section.GetName()};
		pEditor->AddLine("");
		pEditor->AddLine("<color value=\"0.6 0.6 0.2 1.0\">.section</color> {}", name);
		pEditor->AddLine("");

		// these sections are considered as executable
		if (name == "__TEXT,__text" || name == "__TEXT,__stubs")
		{
    		std::unordered_map<std::uint64_t, std::string> names;
    		for (const auto &label : section.GetLabels())
    		    names[label.GetAddress()] = label.GetName();
		
			for (const auto &label : section.GetLabels())
		    {
		        pLabels->AddLine
				(
					"<color value=\"0.7 0.6 0.2 1.0\">{}</color>:"
					"<color value=\"0.8 0.6 0.2 1.0\">{:#016}</color>:"
					"<color value=\"0.6 0.6 0.2 1.0\">{}</color>",
					section.GetName(),
					label.GetAddress(),
					label.GetName()
				);

		        pEditor->AddLine("<color value=\"0.6 0.6 0.2 1.0\">{}</color>:", label.GetName());

				disxx::disasm::Disassembler disasm{};
				const auto &vec
				{
					label.GetData<std::uint32_t>()
						| std::views::all
						| std::views::transform([](const auto &bytes) -> auto { return disxx::disasm::Bytes{bytes}; })
						| std::ranges::to<std::vector<disxx::disasm::Bytes>>()
				};
	   		    for (disxx::disasm::Address addr{label.GetAddress()}; const auto &bytes : vec)
    		    {
					if (const auto &insn{disasm.Disassemble(bytes, addr++)}) [[likely]]
					{
						auto mnemonic
						{
							[insn](void) -> std::string
							{
								auto str{std::format("{}", *insn)};
								
								static const std::regex regs{R"(((b|h|s|d|q|v|w|x)\d{1,2})|(sp)|((w|x)zr))"};
								for (std::sregex_iterator it{str.begin(), str.end(), regs}, end{}; it != end; ++it)
								{
									// Check if it was accidentally confused with immediate operand
									if (const auto prev{str.at(it->position() - 1uz)}; prev == 'x' || std::isdigit(prev) || (prev >= 97 && prev <= 102)) [[unlikely]]
										continue;
									// Check if number of the register is valid
									else if (auto n{0ull}; std::from_chars(it->str().data() + 1, it->str().data() + it->str().size() - 1, n)) [[likely]]
										if (n > 31) [[unlikely]]
											continue;

									str = std::regex_replace
									(
										str,
										std::regex{it->str()},
										std::format("<color value=\"0.3 0.7 0.7 1.0\">{}</color>", it->str())
									);
								}

								static const std::regex imms{R"(#-?((0x[a-f0-9]+)|(\d+\.\d+)))"};
								for (std::sregex_iterator it{str.begin(), str.end(), imms}, end{}; it != end; ++it)
								{
									// Check if it's a pc-relevant address (using .value_or(0) instead of .value() method)
									if (auto insnAddr{insn->GetProgramCounterRelevantAddress()}; insnAddr && std::string{"#"} + MKHEX(insnAddr.value_or(0)) == it->str())
									{
										str = std::regex_replace
										(
											str,
											std::regex{it->str()},
											std::format("<color value=\"0.6 0.6 0.2 1.0\">{}</color>", it->str())
										);
									}
									else
									{
										str = std::regex_replace
										(
											str,
											std::regex{it->str()},
											std::format("<color value=\"0.7 0.2 0.1 1.0\">{}</color>", it->str())
										);
									}
								}

								return str;
							}()
						};
						
						if (auto insnAddr{insn->GetProgramCounterRelevantAddress()})
    		        	{
    		            	if (auto it{names.find(*insnAddr)}; it != names.end())
    		            	{
    		            	    pEditor->AddLine
    		            	    (
									"<color value=\"0.7 0.7 0.7 1.0\">|</color>\t{}\t\t"
									"<color value=\"0.7 0.7 0.7 1.0\">; {:#x}</color>",
    		            	        std::regex_replace
									(
										mnemonic,
										std::regex
										{
											std::string{"#"}
												+ MKHEX(*insnAddr)
										},
										it->second
									),
									label.GetAddress()
								);
	   		            	    
								continue;
	   		            	}
	   		        	}

						pEditor->AddLine("<color value=\"0.7 0.7 0.7 1.0\">|</color>\t{}", mnemonic);
					}
					else	
						pEditor->AddLine("<color value=\"0.7 0.7 0.7 1.0\">|</color>\t{}", insn.error().what());
				}
    		}
		}
		else
		{
			for (const auto &label : section.GetLabels())
			{
				pLabels->AddLine
				(
					"<color value=\"0.7 0.6 0.2 1.0\">{}</color>:"
					"<color value=\"0.8 0.6 0.2 1.0\">{:#016}</color>:"
					"<color value=\"0.6 0.6 0.2 1.0\">{}</color>",
					name,
					label.GetAddress(),
					label.GetName()
				);
				pEditor->AddLine("<color value=\"0.6 0.6 0.2 1.0\">{}</color>:", label.GetName());

				for (const auto &byte : label.GetData<std::uint8_t>())
				{
					pEditor->AddLine
					(
						"<color value=\"0.7 0.7 0.7 1.0\">|</color>"
						"\t<color value=\"0.6 0.6 0.2 1.0\">.byte </color>"
						"<color value=\"0.7 0.2 0.1 1.0\">{:#02x}</color>{}",
						byte,
						std::isprint(byte) && !std::isspace(byte)
							? std::format("\t<color value=\"0.7 0.7 0.7 1.0\">; \'{:c}\'</color>", byte)
							: std::string{}
					);
				}
			}
		}
	}
}

Application *Application::Init(int &argc, char **argv) noexcept(false)
{
	if (argv == nullptr) [[unlikely]]
		throw disxx::utility::error::NullPointerError{"NullPointerError"};
	disxx::ui::MainWindow::InitContext(&argc, argv);
    
	if (!s_pInstance) [[likely]]
        s_pInstance = new Application{};

	static int sArgc{argc};
	static char **sArgv{argv};
	std::set_terminate
	(
		[] -> void
		{
			Application::s_pInstance->m_Logger.LogErr
			(
				sArgc && sArgv
					? sArgv[0]
					: "unknown"
			);
		
			std::string path
			{
				std::filesystem::path
				{
					sArgc && sArgv
						? sArgv[0]
						:
						#ifdef _WIN32
							".\\dis++"
						#else
							"./dis++"
						#endif
				}
				.parent_path()
				.string()
				+ std::filesystem::path::preferred_separator
				+ "reporter"
			};

			std::system(path.c_str());
			std::exit(EXIT_FAILURE);
		}
	);

	return s_pInstance;
}

void Application::Init(void) noexcept(false)
{
	// Destroy the previous window
    std::destroy_at(s_pInstance->m_pInput);

	// Init this window
	s_pInstance->m_pWindow = std::ref
	(
		disxx::ui::MainWindow::Init
		(
			disxx::ui::utility::Vec2<int>
			{
				800,
				600
			},
			"dis++ v" __DISXX_VERSION__
		)
	);
	
	s_pInstance->m_pWindow.get()->SetVisible(true);
	const auto [width, height]{s_pInstance->m_pWindow.get()->GetSize()};
	
	{
		disxx::ui::SourceEditor labels
		{
			0.f,
			height * 0.77f,
			width * 1.f,
			height * 0.23f
		};
		labels.SetColor(0.2f, 0.2f, 0.2f);
		
		s_pInstance->m_pWindow.get()->AddWidget(std::make_unique<disxx::ui::SourceEditor>(labels));
	}

	{
		disxx::ui::Menu menu
		{
			0.f,
			height * 0.97f,
			width * 0.05f,
			height * 0.03f
		};
		menu.SetColor(0.2f, 0.2f, 0.2f);
		menu.SetText("File");

		disxx::ui::MenuEntry entry
		{
			"Open",
			[] -> void
			{
				#ifdef BACKEND_CTX_GLUT
					const auto [w, h]{disxx::ui::backend::GLUTContext::GetWindowSize()};
				#endif
				disxx::ui::TextInput input
				{
					w / 2.f - 100.f,
					h / 2.f - 40.f,
					100.f,
					40.f
				};
				input.SetColor(0.2f, 0.2f, 0.2f);
				s_pInstance->m_pWindow.get()->AddWidget(std::make_unique<disxx::ui::TextInput>(input));

				disxx::ui::Button btn
				{
					w / 2.f - 150.f,
					h / 2.f - 90.f,
					100.f,
					40.f
				};
				btn.SetColor(0.2f, 0.2f, 0.2f);
				btn.SetText("OK");
				btn.SetCallback
				(
					disxx::ui::Button::Trigger::BTN_CLICKED,
					[](const disxx::ui::Widget *const) -> void
					{
						if (s_pInstance->m_pWindow.get()->GetWidgets().size() < 2) [[unlikely]]
							return;

						const auto path
						{
							static_cast<disxx::ui::TextInput *>
							(
								(
									s_pInstance
										->m_pWindow
										.get()
										->GetWidgets()
										.rbegin()
										+ 1
								)->get()
							)->GetText()

						};

						for (const auto _ : std::views::iota(0, 2))
							s_pInstance->m_pWindow.get()->GetWidgets().pop_back();

						if (!path.empty())
							s_pInstance->Disassemble(std::filesystem::path{path});
					}
				);
				s_pInstance->m_pWindow.get()->AddWidget(std::make_unique<disxx::ui::Button>(btn));
			}
		};
		entry.SetColor(0.2f, 0.2f, 0.2f);
		menu.PushEntry(std::move(entry));

		disxx::ui::MenuEntry line
		{
			"Save",
			[] -> void { return; }
		};
		line.SetColor(0.2f, 0.2f, 0.2f);
		menu.PushEntry(std::move(line));

		s_pInstance->m_pWindow.get()->AddWidget(std::make_unique<disxx::ui::Menu>(menu));
	}
	
	{
		disxx::ui::SourceEditor src
		{
			0.f,
			0.f,
			width * 1.f,
			height * 0.75f
		};

		s_pInstance->m_pWindow.get()->AddWidget(std::make_unique<disxx::ui::SourceEditor>(src));
	}

	auto path{s_pInstance->m_pInput->GetPath()};
	s_pInstance->Disassemble(path);

    s_pInstance
		->m_pWindow
		.get()
		->Redisplay();
}

int Application::Exec(void) const noexcept(false)
{
	this->m_pWindow.get()->Exec();
	return EXIT_SUCCESS;
}
