module;

#include <disconf.hpp>

#include <unordered_map>
#include <system_error>
#include <functional>
#include <filesystem>
#include <exception>
#include <charconv>
#include <memory>
#include <ranges>
#include <limits>
#include <format>
#include <vector>
#include <regex>
#include <tuple>
#include <array>
#include <span>

#define MKHEX(x) (std::format("{:#x}", (x)))

module Application;

import disxx.utility.ini.Parser;

import disxx.loader.macho.Loader;
import disxx.disasm.Disassembler;
import disxx.ui.SourceEditor;
import disxx.ui.MainWindow;
import disxx.ui.Button;
import disxx.ui.Widget;
import FileInput;
import DisLog;

// Miscellaneous function(s)
namespace
{
	inline std::tuple<std::string, std::string, std::string> splitver(const std::string &version) noexcept
	{
		std::smatch groups;
		std::regex_match(version, groups, std::regex{R"(^(\d+)\.(\d+)\.(\d+)$)"});
		// Return major minor and patchlevel strings
		return std::make_tuple(groups[1], groups[2], groups[3]);
	}
}

// The only one instance
Application *Application::s_pInstance{nullptr};

Application::Application(std::span<const char *> args) noexcept(false)
	: MainWindow{800, 600}
	, m_Logger{args.data() ? args.at(0) : "[unknown]"}
	, m_Args{args}
	, m_pInput{nullptr}
{
	// Check if args not null
	if (!args.data()) [[unlikely]]
		throw std::invalid_argument{"ArgumentsValueError"};
	
	// Init some glut stuff
	static auto argc{static_cast<int>(args.size() & std::numeric_limits<unsigned int>::max())};
	MainWindow::Init(&argc, const_cast<char **>(args.data()));

	// Init file input window
    this->m_pInput = FileInput::Init(this->m_Args);
    this->m_pInput->SetCallback(__InitFunc);
	if (args.size() > 1)
		this->m_pInput->SetPath(args.at(1));

	// Add some widgets
	this->m_Widgets.emplace_back
	(
		std::make_unique<disxx::ui::SourceEditor>
		(
			0.f,
			this->m_Height * 0.75f,
			this->m_Width,
			this->m_Height * 0.25f
		)
	);
	
	this->m_Widgets.emplace_back
	(
		std::make_unique<disxx::ui::SourceEditor>
		(
			0.f,
			0.f,
			this->m_Width,
			this->m_Height * 0.75f
		)
	);

	// Init some widgets
	this->m_Widgets.at(0)->SetColor(0.2f, 0.2f, 0.2f);
	const auto &ptr{reinterpret_cast<disxx::ui::SourceEditor *>(this->m_Widgets.at(1).get())};
	ptr->SetColor(0.2f, 0.2f, 0.2f);

	ptr->AddLine(";{:*<64}", "");
    ptr->AddLine(";  This file was generated by the dis++ disassembler");
    ptr->AddLine(";\tCopyright (C) ultimatum");
    ptr->AddLine(";  Dis++ version: " __DISXX_VERSION__);
    ptr->AddLine(";{:*<64}", "");
    ptr->AddLine("");
    ptr->AddLine(";{:=<63};", "");
	ptr->AddLine("");
}

Application::~Application(void) noexcept
{
	if (this->m_pInput) [[likely]]
		delete this->m_pInput;
}

Application *Application::Init(int &argc, const char *argv[]) noexcept(false)
{
    if (!s_pInstance) [[likely]]
        s_pInstance = new Application{std::span<const char *>(argv, argc)};
    
	std::set_terminate
	(
		[](void) -> void
		{
			s_pInstance->DestroyWindow();

			Application::s_pInstance->m_Logger.LogErr();
		
			std::string path
			{
				std::filesystem::path
				{
					Application::s_pInstance->m_Args.data()
						? Application::s_pInstance->m_Args.at(0)
						:
						#ifdef _WIN32
							".\\dis++"
						#else
							"./dis++"
						#endif
				}
				.parent_path()
				.string()
				+ std::filesystem::path::preferred_separator
				+ "reporter"
			};

			std::system(path.c_str());
			std::exit(EXIT_FAILURE);
		}
	);

	return s_pInstance;
}

void Application::__InitFunc([[maybe_unused]] const disxx::ui::MainWindow *const ptr) noexcept(false)
{
	// Check if path exists
	auto path{s_pInstance->m_pInput->GetPath()};
	if (std::error_code errc{}; !std::filesystem::exists(path, errc)) [[unlikely]]
		throw std::filesystem::filesystem_error{"FileNotFoundError", errc};

	// Init this window
	s_pInstance->m_Win = s_pInstance->CreateWindow
	(
		disxx::ui::utility::Vec2<int>
		{
			s_pInstance->m_Width,
			s_pInstance->m_Height
		},
		std::format("dis++ v" __DISXX_VERSION__ " - {}", path.string()).c_str()
	);
	s_pInstance->SwitchWindow(s_pInstance->m_Win);

	/* Set up callbacks */
	s_pInstance->SetDisplayCallback
    (
        [](void) -> void
        { s_pInstance->__DisplayFunc(); }
    );

	s_pInstance->SetReshapeCallback
    (
        [](int width, int height) -> void
        { s_pInstance->__ReshapeFunc(width, height); }
    );

	s_pInstance->SetKeyboardCallback
    (
        [](unsigned char key, int x, int y) -> void
        { s_pInstance->__KeyboardFunc(key, x, y); }
    );

    s_pInstance->SetMouseButtonCallback
    (
		[](int button, int state, int x, int y) -> void
		{ s_pInstance->__MouseFunc(button, state, x, y); }
    );

    s_pInstance->SetMouseMotionCallback
    (
        [](int x, int y) -> void
        { s_pInstance->__MotionFunc(x, y); }
    );

	// Destroy the previous window
    std::destroy_at(s_pInstance->m_pInput);

	// Just take the ptrs, so I shouldn't cast it every time
	auto *pLabels{reinterpret_cast<disxx::ui::SourceEditor *>(s_pInstance->m_Widgets.at(0).get())};
	auto *pEditor{reinterpret_cast<disxx::ui::SourceEditor *>(s_pInstance->m_Widgets.at(1).get())};

	// Load the executable
    disxx::loader::macho::Loader ldr;
	ldr.LoadFile(path);
	
	// Load metadata of the executable
	auto info{ldr.LoadMetadata()};
	pEditor->AddLine(";{:*<28}METADATA{:*<28}", "", "");
	pEditor->AddLine(";  File path: {}", path.string());
	pEditor->AddLine(";  File type: Mach-O {}", ldr.GetFileType());	
	pEditor->AddLine(";  Target OS: {}, v{}", info.GetPlatformName(), info.GetPlatformMinVersion());
	ldr
		.LoadImageBase()
		.and_then
		(
			[pEditor](const auto &addr) -> std::optional<long long int>
			{ 
				pEditor->AddLine(";\tImage base: {}", MKHEX(addr));
				return addr;
			}
		).or_else
		(
			[pEditor](void) -> std::optional<long long int>
			{
				pEditor->AddLine("\tImage base: unknown");
				return std::nullopt; 
			}
		);
	for (const auto &[name, version] : info.GetBuildTools())
		pEditor->AddLine(";  Build tool: {}, v{}", name, version);
	pEditor->AddLine(";{:*<64}", "");
	pEditor->AddLine("");

	const auto &[platformMajor, platformMinor, _]{::splitver(info.GetPlatformMinVersion())};
	const auto &[sdkMajor, sdkMinor, _]{::splitver(info.GetSDKVersion())};
	pEditor->AddLine
	(
		"<color value=\"0.6 0.6 0.2 1.0\">.build_version</color>"
		" {}, <color value=\"0.7 0.2 0.1 1.0\">{}</color>,"
		" <color value=\"0.7 0.2 0.1 1.0\">{}</color>"
		" sdk_version <color value=\"0.7 0.2 0.1 1.0\">{}</color>,"
		" <color value=\"0.7 0.2 0.1 1.0\">{}</color>",
		info.GetPlatformName()
			| std::views::all
			| std::views::transform(::tolower)
			| std::ranges::to<std::string>(),
		platformMajor,
		platformMinor,
		sdkMajor,
		sdkMinor
	);

	for (auto sections{ldr.LoadSections()}; auto &section : sections)
	{
		ldr.LoadSectionData(section);
	
		auto name{section.GetSectionName()};
		pEditor->AddLine("");
		pEditor->AddLine("<color value=\"0.6 0.6 0.2 1.0\">.section</color> {}", name);
		pEditor->AddLine("");

		// Only "__TEXT,__text" section considers as executable
		if (name == "__TEXT,__text")
		{
			const auto &labelsAndData{section.GetData<std::uint32_t>()};
    		std::unordered_map<std::uint64_t, std::string> names;
    		for (const auto &[label, _] : labelsAndData)
    		    names[label.vaddr] = label.name;
			
			for (const auto &[func, data] : labelsAndData)
		    {
		        pLabels->AddLine
				(
					"<color value=\"0.7 0.6 0.2 1.0\">{}</color>:"
					"<color value=\"0.8 0.6 0.2 1.0\">{:#016}</color>:"
					"<color value=\"0.6 0.6 0.2 1.0\">{}</color>",
					name,
					func.vaddr,
					names[func.vaddr]
				);

		        pEditor->AddLine("<color value=\"0.6 0.6 0.2 1.0\">{}</color>:", names[func.vaddr]);
	
				std::vector<disxx::disasm::Bytes> vec
				{
					data
						| std::views::all
						| std::views::transform([](auto &bytes) -> disxx::disasm::Bytes { return disxx::disasm::Bytes{bytes}; })
						| std::ranges::to<std::vector<disxx::disasm::Bytes>>()
				};

	   		    for (const disxx::disasm::Disassembler disasm{true}; const auto &insn : disasm.DisassembleAll(vec | std::views::all, disxx::disasm::Address{func.vaddr}))
    		    {
					if (insn)
					{
						const auto &value{insn.value()};
						auto mnemonic
						{
							[value](void) -> std::string
							{
								auto mnemonic{std::format("{}", value)};
								
								static const std::regex regs{R"(((b|h|s|d|q|v|w|x)\d{1,2})|(sp)|((w|x)zr))"};
								for (std::sregex_iterator it{mnemonic.begin(), mnemonic.end(), regs}, end{}; it != end; ++it)
								{
									// Check if it was accidentally confused with immediate operand
									if (const auto prev{mnemonic.at(it->position() - 1)}; prev == 'x' || std::isdigit(prev) || (prev >= 97 && prev <= 102)) [[unlikely]]
										continue;
									// Check if number of the register is valid
									else if (auto n{0ull}; std::from_chars(it->str().data() + 1, it->str().data() + it->str().size() - 1, n)) [[likely]]
										if (n < 0 || n > 31) [[unlikely]]
											continue;
	
									mnemonic = std::regex_replace
									(
										mnemonic,
										std::regex{it->str()},
										std::format("<color value=\"0.3 0.7 0.7 1.0\">{}</color>", it->str())
									);
								}

								static const std::regex imms{R"(#-?((0x[a-f0-9]+)|(\d+\.\d+)))"};
								for (std::sregex_iterator it{mnemonic.begin(), mnemonic.end(), imms}, end{}; it != end; ++it)
								{
									// Check if it's a pc-relevant address (using .value_or(0) instead of .value() method)
									if (auto addr{value.GetProgramCounterRelevantAddress()}; addr && std::string{"#"} + MKHEX(addr.value_or(0)) == it->str())
									{
										mnemonic = std::regex_replace
										(
											mnemonic,
											std::regex{it->str()},
											std::format("<color value=\"0.6 0.6 0.2 1.0\">{}</color>", it->str())
										);
									}
									else
									{
										mnemonic = std::regex_replace
										(
											mnemonic,
											std::regex{it->str()},
											std::format("<color value=\"0.7 0.2 0.1 1.0\">{}</color>", it->str())
										);
									}
								}

								return mnemonic;
							}()
						};

						if (auto addr{value.GetProgramCounterRelevantAddress()})
    		        	{
    		            	if (auto it{names.find(*addr)}; it != names.end())
    		            	{
    		            	    pEditor->AddLine
    		            	    (
									"<color value=\"0.7 0.7 0.7 1.0\">|</color>\t{}\t\t"
									"<color value=\"0.7 0.7 0.7 1.0\">; {:#x}</color>",
    		            	        std::regex_replace
									(
										mnemonic,
										std::regex
										{
											std::string{"#"}
												+ MKHEX(*addr)
										},
										it->second
									),
									func.vaddr
								);
	   		            	    
								continue;
	   		            	}
	   		        	}

						pEditor->AddLine("<color value=\"0.7 0.7 0.7 1.0\">|</color>\t{}", mnemonic);
						continue;
					}
		
					pEditor->AddLine("<color value=\"0.7 0.7 0.7 1.0\">|</color>\t{}", insn.error().what());
				}
    		}
		}
		else
		{
			for (const auto &[label, data] : section.GetData<std::uint8_t>())
			{
				pLabels->AddLine
				(
					"<color value=\"0.7 0.6 0.2 1.0\">{}</color>:"
					"<color value=\"0.8 0.6 0.2 1.0\">{:#016}</color>:"
					"<color value=\"0.6 0.6 0.2 1.0\">{}</color>",
					name,
					label.vaddr,
					label.name
				);

		        pEditor->AddLine("<color value=\"0.6 0.6 0.2 1.0\">{}</color>:", label.name);

				for (const auto &byte : data)
				{
					pEditor->AddLine
					(
						"<color value=\"0.7 0.7 0.7 1.0\">|</color>"
						"\t<color value=\"0.6 0.6 0.2 1.0\">.byte </color>"
						"<color value=\"0.7 0.2 0.1 1.0\">{:#02x}</color>{}",
						byte,
						std::isprint(byte) && !std::isspace(byte)
							? std::format("\t<color value=\"0.7 0.7 0.7 1.0\">; \'{:c}\'</color>", byte)
							: std::string{}
					);
				}
			}
		}
	}

	s_pInstance->__ReshapeFunc(s_pInstance->m_Width, s_pInstance->m_Height);
	
    s_pInstance->Redisplay();
}

void Application::__KeyboardFunc(unsigned char key, int x, int y) noexcept(false)
{
	for (auto &pWidget : this->m_Widgets)
		pWidget->HandleKeyboard(key, x, y);
	this->Redisplay();
}

void Application::__MouseFunc(int button, int state, int x, int y) noexcept(false)
{
	for (auto &pWidget : this->m_Widgets)
		pWidget->HandleMouse(button, state, x, y);
	this->Redisplay();
}

void Application::__ReshapeFunc(int width, int height) noexcept(false)
{
	this->m_Width = width;
	this->m_Height = height;

    this->m_Widgets.at(0)->Resize(this->m_Width, this->m_Height * 0.25f);
	this->m_Widgets.at(0)->Replace(0.f, this->m_Height * 0.75f);
	this->m_Widgets.at(1)->Resize
	(
		this->m_Width,
		this->m_Height * 0.75f
	);

	this->Redisplay();    
}

void Application::__MotionFunc(int x, int y) noexcept(false)
{
	for (auto &pWidget : this->m_Widgets)
		pWidget->HandleMotion(x, y);
	this->Redisplay();
}

void Application::__DisplayFunc(void) noexcept
{
	for (const auto &pWidget : this->m_Widgets)
		pWidget->Render();
	this->SwapBuffers();
	disxx::ui::Widget::ClearBuffers();
}

[[nodiscard]] int Application::Exec(void) const noexcept(false)
{
	this->ExecLoop();
	return EXIT_SUCCESS;
}
